#include "solar/settings/setting.cpp"
#include "solar/settings/setting_group.cpp"
#include "solar/settings/setting_registry.cpp"
#include "solar/settings/bool_setting.cpp"
#include "solar/settings/int_setting.cpp"
