#include "solar/archiving/auto_versioned_json_archive_helpers.cpp"
#include "solar/archiving/json_archive_reader.cpp"
#include "solar/archiving/json_archive_writer.cpp"
#include "solar/archiving/binary_archive_reader.cpp"
#include "solar/archiving/binary_archive_writer.cpp"
#include "solar/archiving/archivable_cloning.cpp"
