#include "solar/input/mouse_button.cpp"
#include "solar/input/keyboard_key.cpp"
#include "solar/input/input_mapping.cpp"
#include "solar/input/input_mappings.cpp"
#include "solar/input/input_mapping_modifiers.cpp"
